/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
	kueuev1beta1 "sigs.k8s.io/kueue/client-go/applyconfiguration/kueue/v1beta1"
)

// FakeMinWaitConfigs implements MinWaitConfigInterface
type FakeMinWaitConfigs struct {
	Fake *FakeKueueV1beta1
}

var minwaitconfigsResource = v1beta1.SchemeGroupVersion.WithResource("minwaitconfigs")

var minwaitconfigsKind = v1beta1.SchemeGroupVersion.WithKind("MinWaitConfig")

// Get takes name of the minWaitConfig, and returns the corresponding minWaitConfig object, and an error if there is any.
func (c *FakeMinWaitConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.MinWaitConfig, err error) {
	emptyResult := &v1beta1.MinWaitConfig{}
	obj, err := c.Fake.
		Invokes(testing.NewRootGetActionWithOptions(minwaitconfigsResource, name, options), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.MinWaitConfig), err
}

// List takes label and field selectors, and returns the list of MinWaitConfigs that match those selectors.
func (c *FakeMinWaitConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.MinWaitConfigList, err error) {
	emptyResult := &v1beta1.MinWaitConfigList{}
	obj, err := c.Fake.
		Invokes(testing.NewRootListActionWithOptions(minwaitconfigsResource, minwaitconfigsKind, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.MinWaitConfigList{ListMeta: obj.(*v1beta1.MinWaitConfigList).ListMeta}
	for _, item := range obj.(*v1beta1.MinWaitConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested minWaitConfigs.
func (c *FakeMinWaitConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchActionWithOptions(minwaitconfigsResource, opts))
}

// Create takes the representation of a minWaitConfig and creates it.  Returns the server's representation of the minWaitConfig, and an error, if there is any.
func (c *FakeMinWaitConfigs) Create(ctx context.Context, minWaitConfig *v1beta1.MinWaitConfig, opts v1.CreateOptions) (result *v1beta1.MinWaitConfig, err error) {
	emptyResult := &v1beta1.MinWaitConfig{}
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateActionWithOptions(minwaitconfigsResource, minWaitConfig, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.MinWaitConfig), err
}

// Update takes the representation of a minWaitConfig and updates it. Returns the server's representation of the minWaitConfig, and an error, if there is any.
func (c *FakeMinWaitConfigs) Update(ctx context.Context, minWaitConfig *v1beta1.MinWaitConfig, opts v1.UpdateOptions) (result *v1beta1.MinWaitConfig, err error) {
	emptyResult := &v1beta1.MinWaitConfig{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateActionWithOptions(minwaitconfigsResource, minWaitConfig, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.MinWaitConfig), err
}

// Delete takes name of the minWaitConfig and deletes it. Returns an error if one occurs.
func (c *FakeMinWaitConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(minwaitconfigsResource, name, opts), &v1beta1.MinWaitConfig{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMinWaitConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionActionWithOptions(minwaitconfigsResource, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.MinWaitConfigList{})
	return err
}

// Patch applies the patch and returns the patched minWaitConfig.
func (c *FakeMinWaitConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.MinWaitConfig, err error) {
	emptyResult := &v1beta1.MinWaitConfig{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(minwaitconfigsResource, name, pt, data, opts, subresources...), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.MinWaitConfig), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied minWaitConfig.
func (c *FakeMinWaitConfigs) Apply(ctx context.Context, minWaitConfig *kueuev1beta1.MinWaitConfigApplyConfiguration, opts v1.ApplyOptions) (result *v1beta1.MinWaitConfig, err error) {
	if minWaitConfig == nil {
		return nil, fmt.Errorf("minWaitConfig provided to Apply must not be nil")
	}
	data, err := json.Marshal(minWaitConfig)
	if err != nil {
		return nil, err
	}
	name := minWaitConfig.Name
	if name == nil {
		return nil, fmt.Errorf("minWaitConfig.Name must be provided to Apply")
	}
	emptyResult := &v1beta1.MinWaitConfig{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(minwaitconfigsResource, *name, types.ApplyPatchType, data, opts.ToPatchOptions()), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.MinWaitConfig), err
}
