/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	v1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
	kueuev1beta1 "sigs.k8s.io/kueue/client-go/applyconfiguration/kueue/v1beta1"
	scheme "sigs.k8s.io/kueue/client-go/clientset/versioned/scheme"
)

// MinWaitConfigsGetter has a method to return a MinWaitConfigInterface.
// A group's client should implement this interface.
type MinWaitConfigsGetter interface {
	MinWaitConfigs() MinWaitConfigInterface
}

// MinWaitConfigInterface has methods to work with MinWaitConfig resources.
type MinWaitConfigInterface interface {
	Create(ctx context.Context, minWaitConfig *v1beta1.MinWaitConfig, opts v1.CreateOptions) (*v1beta1.MinWaitConfig, error)
	Update(ctx context.Context, minWaitConfig *v1beta1.MinWaitConfig, opts v1.UpdateOptions) (*v1beta1.MinWaitConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.MinWaitConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.MinWaitConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.MinWaitConfig, err error)
	Apply(ctx context.Context, minWaitConfig *kueuev1beta1.MinWaitConfigApplyConfiguration, opts v1.ApplyOptions) (result *v1beta1.MinWaitConfig, err error)
	MinWaitConfigExpansion
}

// minWaitConfigs implements MinWaitConfigInterface
type minWaitConfigs struct {
	*gentype.ClientWithListAndApply[*v1beta1.MinWaitConfig, *v1beta1.MinWaitConfigList, *kueuev1beta1.MinWaitConfigApplyConfiguration]
}

// newMinWaitConfigs returns a MinWaitConfigs
func newMinWaitConfigs(c *KueueV1beta1Client) *minWaitConfigs {
	return &minWaitConfigs{
		gentype.NewClientWithListAndApply[*v1beta1.MinWaitConfig, *v1beta1.MinWaitConfigList, *kueuev1beta1.MinWaitConfigApplyConfiguration](
			"minwaitconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1beta1.MinWaitConfig { return &v1beta1.MinWaitConfig{} },
			func() *v1beta1.MinWaitConfigList { return &v1beta1.MinWaitConfigList{} }),
	}
}
